"""empty message

Revision ID: ef8a98ef3a0e
Revises: dfa8de426da4
Create Date: 2020-08-20 09:51:59.864364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8a98ef3a0e'
down_revision = 'dfa8de426da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DeleteShow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeleteShow',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='DeleteShow_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='DeleteShow_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id', name='DeleteShow_pkey')
    )
    # ### end Alembic commands ###
